apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okk-ingress
  namespace: okk
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: okk.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: okk-service
            port:
              number: 5000
